---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-db-fatiudeen-dev-v1-database
  failurePolicy: Fail
  name: vdatabase.kb.io
  rules:
  - apiGroups:
    - db.fatiudeen.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - databases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-db-fatiudeen-dev-v1-datastore
  failurePolicy: Fail
  name: vdatastore.kb.io
  rules:
  - apiGroups:
    - db.fatiudeen.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - datastores
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-db-fatiudeen-dev-v1-role
  failurePolicy: Fail
  name: vrole.kb.io
  rules:
  - apiGroups:
    - db.fatiudeen.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - roles
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-db-fatiudeen-dev-v1-user
  failurePolicy: Fail
  name: vuser.kb.io
  rules:
  - apiGroups:
    - db.fatiudeen.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - users
  sideEffects: None
