# permissions for end users to edit migrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dbchan
    app.kubernetes.io/managed-by: kustomize
  name: migration-editor-role
rules:
- apiGroups:
  - db.fatiudeen.dev
  resources:
  - migrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.fatiudeen.dev
  resources:
  - migrations/status
  verbs:
  - get
