apiVersion: db.fatiudeen.dev/v1
kind: Database
metadata:
  labels:
    app.kubernetes.io/name: dbchan
    app.kubernetes.io/managed-by: kustomize
  name: database-sample
spec:
  # TODO(user): Add fields here
