apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dbchan.fullname" . }}-datastore-editor-role
  labels:
  {{- include "dbchan.labels" . | nindent 4 }}
rules:
- apiGroups:
  - db.fatiudeen.dev
  resources:
  - datastores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.fatiudeen.dev
  resources:
  - datastores/status
  verbs:
  - get
