controllerManager:
  manager:
    args:
    - --leader-elect
    - --health-probe-bind-address=:8081
    - --zap-log-level=debug
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: fatiudeen/dbchan
      tag: "v0.1.0"
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  podSecurityContext:
    runAsNonRoot: true
  replicas: 1
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
