name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
    paths:
      - 'config/**'
      - 'Makefile'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
      - 'cmd/**'
      - 'internal/**'
      - 'api/**'
    tags: [ 'v*' ]
    

env:
  REGISTRY: fatiudeen
  IMAGE_NAME: dbchan
  IMAGE_TAG: ${{ github.ref_name }}-${{ github.run_number }}

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    
    - name: Build project
      run: make build
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push Docker image
      run: make docker-buildx IMG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

